FROM ubuntu:latest
RUN apt-get update && apt-get install -y python3 python3-pip
COPY requirements.txt .
RUN pip3 install -r requirements.txt
COPY . .
CMD ["python3", "./app.py"]
# Create requirements.txt: 
# flask
# Create app.py: 
# from flask import Flask
# app = Flask(__name__)
# 
# @app.route('/')
# def hello_world():
#     return 'Hello, World!' 
# 
# if __name__ == '__main__':
#     app.run(debug=True, host='0.0.0.0') 